# Default-deny the local build context, then keep only Go build inputs.
**
!go.mod
!go.sum
!main.go
!favicon.ico

!bootstrap/
!bootstrap/*.go
!certificates/
!certificates/*.go
!config/
!config/*.go
!dcdn/
!dcdn/*.go
!ddns/
!ddns/*.go
!forward/
!forward/*.go
!helper/
!helper/*.go
!helper/update/
!helper/update/*.go
!signer/
!signer/*.go
!web/
!web/*.go
!web/*.html
!webservice/
!webservice/*.go
!webservice/*.html
!webservice/favicon.ico
!webservice/librespeed/
!webservice/librespeed/**
!static/
!static/**

# Tests are not needed to compile the production image.
**/*_test.go
