name: Bug report
description: Report a bug to help us improve D-NET

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Tell us what issues you ran into
      placeholder: Include information about what you tried, what you expected to happen, and what actually happened. The more details, the better!
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Service type
      description: The service type you are using.
      multiple: true
      options:
        - DCDN
        - DDNS
  - type: dropdown
    attributes:
      label: Service type provider
      description: The service type provider you are using.
      multiple: true
      options:
        - 阿里云
        - 腾讯云
        - DnsPod
        - Cloudflare
        - 华为云
        - Callback
        - 百度云
        - Porkbun
        - GoDaddy
        - Namecheap
        - NameSilo
        - Vercel
        - Dynadot
        - Others
  - type: dropdown
    attributes:
      label: Did you search for similar issues before submitting this one?
      options:
        - No, I didn't.
        - Yes, I did, but I didn't find anything useful.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: The operating system you are running D-NET on
      options:
        - Linux
        - Windows
        - macOS (Darwin)
        - FreeBSD
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Architecture
      description: The architecture you are running D-NET on
      options:
        - i386
        - x86_64
        - armv5
        - armv6
        - armv7
        - arm64
        - mips
        - mipsle
        - mips64
        - mips64le
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: The version of D-NET you are using
      placeholder: v0.0.1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How are you running D-NET ?
      options:
        - Docker
        - Service
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any other information
      description: |
        Please provide the steps to reproduce the bug.
        Or any other screenshots or logs that might help us understand the issue better.
